# run as ansible-playbook refresh_dali.yaml" 
---
- name: Execute a script.
  hosts: 'dali'
  remote_user: 'root'
  tasks:
     - name: Execute the script
       command: rm -rf /var/lib/HPCCSystems/myroxie/uslaves
