# run as ansible-playbook restart_thor.yaml --extra-vars "hosts=dali" 
---
- name: Execute a script.
  hosts: '{{ hosts }}'
  remote_user: 'root'
  tasks:
     - name: Execute the script
       command: bash /etc/init.d/hpcc-init -c mythor restart
