# run as ansible-playbook start_hpcc.yaml --extra-vars "hosts=dali" 
# run as ansible-playbook start_hpcc.yaml --extra-vars "hosts=non-dali" 
# run as ansible-playbook start_hpcc.yaml --extra-vars "hosts=hpcc" 
---
- name: Execute a script.
  hosts: '{{ hosts }}'
  remote_user: 'root'
  tasks:
     - name: Execute the script
       command: bash /etc/init.d/hpcc-init start
